<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>True</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Headless" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageVersion Include="BB84.EntityFrameworkCore.Entities" Version="5.0.916" />
    <PackageVersion Include="BB84.EntityFrameworkCore.Repositories" Version="5.0.916" />
    <PackageVersion Include="BB84.EntityFrameworkCore.Repositories.Abstractions" Version="5.0.916" />
    <PackageVersion Include="BB84.Extensions" Version="5.0.916" />
    <PackageVersion Include="BB84.Notifications" Version="5.0.726" />
    <PackageVersion Include="BB84.SourceGenerators" Version="2.4.903" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="MSTest" Version="4.4.1" />
    <PackageVersion Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.17" />
  </ItemGroup>
</Project>