//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB84.IPTV.M3U.Editor.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB84.IPTV.M3U.Editor.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels added to the playlist &apos;{1}&apos;..
        /// </summary>
        public static string CatalogChannelsAdded {
            get {
                return ResourceManager.GetString("CatalogChannelsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels found..
        /// </summary>
        public static string CatalogChannelsFound {
            get {
                return ResourceManager.GetString("CatalogChannelsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlist is open. Open a playlist first, the channels are added to it..
        /// </summary>
        public static string CatalogNoPlaylistOpen {
            get {
                return ResourceManager.GetString("CatalogNoPlaylistOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel operation failed..
        /// </summary>
        public static string CatalogOperationFailed {
            get {
                return ResourceManager.GetString("CatalogOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} — {2} channels found..
        /// </summary>
        public static string CatalogPageStatus {
            get {
                return ResourceManager.GetString("CatalogPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language has been changed. Do you want to restart the application to apply the changes?.
        /// </summary>
        public static string ChangedLanguageRestartApplicationQuestion {
            get {
                return ResourceManager.GetString("ChangedLanguageRestartApplicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the application language to &apos;{0}&apos;?.
        /// </summary>
        public static string ChangeLanguageQuestion {
            get {
                return ResourceManager.GetString("ChangeLanguageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom channel &apos;{0}&apos; saved..
        /// </summary>
        public static string CustomChannelSaved {
            get {
                return ResourceManager.GetString("CustomChannelSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the custom channel &apos;{0}&apos;? This cannot be undone..
        /// </summary>
        public static string DeleteCustomChannelQuestion {
            get {
                return ResourceManager.GetString("DeleteCustomChannelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the playlist &apos;{0}&apos;? This cannot be undone..
        /// </summary>
        public static string DeletePlaylistQuestion {
            get {
                return ResourceManager.GetString("DeletePlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        public static string ExitApplicationQuestion {
            get {
                return ResourceManager.GetString("ExitApplicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Playlist.
        /// </summary>
        public static string ExportPlaylistTitle {
            get {
                return ResourceManager.GetString("ExportPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Playlist.
        /// </summary>
        public static string ImportPlaylistTitle {
            get {
                return ResourceManager.GetString("ImportPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export channels.xml.
        /// </summary>
        public static string GuideExportTitle {
            get {
                return ResourceManager.GetString("GuideExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels written to &apos;{1}&apos;..
        /// </summary>
        public static string GuideExported {
            get {
                return ResourceManager.GetString("GuideExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} entries can be grabbed..
        /// </summary>
        public static string GuideMappingStatus {
            get {
                return ResourceManager.GetString("GuideMappingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mappings saved..
        /// </summary>
        public static string GuideMappingsSaved {
            get {
                return ResourceManager.GetString("GuideMappingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No guide is known for this entry..
        /// </summary>
        public static string GuideNoOptions {
            get {
                return ResourceManager.GetString("GuideNoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guide operation failed..
        /// </summary>
        public static string GuideOperationFailed {
            get {
                return ResourceManager.GetString("GuideOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} guides known for this entry..
        /// </summary>
        public static string GuideOptionsStatus {
            get {
                return ResourceManager.GetString("GuideOptionsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}, {2} guides..
        /// </summary>
        public static string GuideSitePageStatus {
            get {
                return ResourceManager.GetString("GuideSitePageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sites known..
        /// </summary>
        public static string GuideSitesStatus {
            get {
                return ResourceManager.GetString("GuideSitesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cached logos deleted..
        /// </summary>
        public static string LogoCacheCleared {
            get {
                return ResourceManager.GetString("LogoCacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logos downloaded..
        /// </summary>
        public static string LogoCacheDownloaded {
            get {
                return ResourceManager.GetString("LogoCacheDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo cache failed..
        /// </summary>
        public static string LogoCacheFailed {
            get {
                return ResourceManager.GetString("LogoCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading logos: {0} of {1}..
        /// </summary>
        public static string LogoCacheProgress {
            get {
                return ResourceManager.GetString("LogoCacheProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} logos could not be cached, see the log file for what went wrong..
        /// </summary>
        public static string LogoCacheSkipped {
            get {
                return ResourceManager.GetString("LogoCacheSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} logos cached..
        /// </summary>
        public static string LogoCacheStatus {
            get {
                return ResourceManager.GetString("LogoCacheStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} missing.
        /// </summary>
        public static string LogoCacheMissing {
            get {
                return ResourceManager.GetString("LogoCacheMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; created..
        /// </summary>
        public static string MergeCompleted {
            get {
                return ResourceManager.GetString("MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged Playlist.
        /// </summary>
        public static string MergedPlaylistName {
            get {
                return ResourceManager.GetString("MergedPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least two playlists to merge..
        /// </summary>
        public static string MergeNeedsTwoPlaylists {
            get {
                return ResourceManager.GetString("MergeNeedsTwoPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The merge failed..
        /// </summary>
        public static string MergeOperationFailed {
            get {
                return ResourceManager.GetString("MergeOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Playlist.
        /// </summary>
        public static string MergePlaylistTitle {
            get {
                return ResourceManager.GetString("MergePlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} playlists, {1} entries, {2} duplicates dropped..
        /// </summary>
        public static string MergePreviewStatus {
            get {
                return ResourceManager.GetString("MergePreviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The merge has no playlists to merge..
        /// </summary>
        public static string MergeWithoutSources {
            get {
                return ResourceManager.GetString("MergeWithoutSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Channel.
        /// </summary>
        public static string NewCustomChannelName {
            get {
                return ResourceManager.GetString("NewCustomChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        public static string NewPlaylistName {
            get {
                return ResourceManager.GetString("NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PageStatus {
            get {
                return ResourceManager.GetString("PageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist cannot be saved: {0}.
        /// </summary>
        public static string PlaylistCannotBeSaved {
            get {
                return ResourceManager.GetString("PlaylistCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entries have no URL..
        /// </summary>
        public static string PlaylistEntriesWithoutUrl {
            get {
                return ResourceManager.GetString("PlaylistEntriesWithoutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; exported to &apos;{1}&apos;..
        /// </summary>
        public static string PlaylistExported {
            get {
                return ResourceManager.GetString("PlaylistExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; imported..
        /// </summary>
        public static string PlaylistImported {
            get {
                return ResourceManager.GetString("PlaylistImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist needs a name..
        /// </summary>
        public static string PlaylistNameRequired {
            get {
                return ResourceManager.GetString("PlaylistNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist operation failed..
        /// </summary>
        public static string PlaylistOperationFailed {
            get {
                return ResourceManager.GetString("PlaylistOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; saved..
        /// </summary>
        public static string PlaylistSaved {
            get {
                return ResourceManager.GetString("PlaylistSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data paths have been changed. Do you want to restart the application to apply the changes?.
        /// </summary>
        public static string ChangedDataPathsRestartApplicationQuestion {
            get {
                return ResourceManager.GetString("ChangedDataPathsRestartApplicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that holds the database.
        /// </summary>
        public static string DataDirectoryDialogTitle {
            get {
                return ResourceManager.GetString("DataDirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; cannot be used, please enter a full path..
        /// </summary>
        public static string DataPathIsNotValid {
            get {
                return ResourceManager.GetString("DataPathIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that holds the log files.
        /// </summary>
        public static string LogDirectoryDialogTitle {
            get {
                return ResourceManager.GetString("LogDirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory that holds the cached logos.
        /// </summary>
        public static string LogoDirectoryDialogTitle {
            get {
                return ResourceManager.GetString("LogoDirectoryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database could not be checked..
        /// </summary>
        public static string DatabaseCheckFailed {
            get {
                return ResourceManager.GetString("DatabaseCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database could not be created..
        /// </summary>
        public static string DatabaseCreateFailed {
            get {
                return ResourceManager.GetString("DatabaseCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database could not be imported..
        /// </summary>
        public static string DatabaseImportFailed {
            get {
                return ResourceManager.GetString("DatabaseImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database import has started..
        /// </summary>
        public static string DatabaseImportStarted {
            get {
                return ResourceManager.GetString("DatabaseImportStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0}: {1} records ({2} of {3})..
        /// </summary>
        public static string DatabaseImportProgressStatus {
            get {
                return ResourceManager.GetString("DatabaseImportProgressStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is done, {0} records in total..
        /// </summary>
        public static string DatabaseImportSucceeded {
            get {
                return ResourceManager.GetString("DatabaseImportSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is done, no records were imported..
        /// </summary>
        public static string DatabaseImportWithoutRecords {
            get {
                return ResourceManager.GetString("DatabaseImportWithoutRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist in &apos;{0}&apos; could not be read..
        /// </summary>
        public static string PlaylistFileLoadFailed {
            get {
                return ResourceManager.GetString("PlaylistFileLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist in &apos;{0}&apos; has been read..
        /// </summary>
        public static string PlaylistFileLoaded {
            get {
                return ResourceManager.GetString("PlaylistFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the playlist in &apos;{0}&apos;..
        /// </summary>
        public static string PlaylistFileLoading {
            get {
                return ResourceManager.GetString("PlaylistFileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist could not be written to &apos;{0}&apos;..
        /// </summary>
        public static string PlaylistFileSaveFailed {
            get {
                return ResourceManager.GetString("PlaylistFileSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist has been written to &apos;{0}&apos;..
        /// </summary>
        public static string PlaylistFileSaved {
            get {
                return ResourceManager.GetString("PlaylistFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing the playlist to &apos;{0}&apos;..
        /// </summary>
        public static string PlaylistFileSaving {
            get {
                return ResourceManager.GetString("PlaylistFileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be read..
        /// </summary>
        public static string SettingsLoadFailed {
            get {
                return ResourceManager.GetString("SettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be managed..
        /// </summary>
        public static string SettingsOperationFailed {
            get {
                return ResourceManager.GetString("SettingsOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings could not be written..
        /// </summary>
        public static string SettingsSaveFailed {
            get {
                return ResourceManager.GetString("SettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be read from iptv-org..
        /// </summary>
        public static string WebRequestFailed {
            get {
                return ResourceManager.GetString("WebRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist &apos;{0}&apos; has unsaved changes. Do you want to save them?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
    }
}
