//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB84.IPTV.M3U.Editor.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB84.IPTV.M3U.Editor.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels added to the playlist &apos;{1}&apos;..
        /// </summary>
        internal static string CatalogChannelsAdded {
            get {
                return ResourceManager.GetString("CatalogChannelsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} channels found..
        /// </summary>
        internal static string CatalogChannelsFound {
            get {
                return ResourceManager.GetString("CatalogChannelsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlist is open. Open a playlist first, the channels are added to it..
        /// </summary>
        internal static string CatalogNoPlaylistOpen {
            get {
                return ResourceManager.GetString("CatalogNoPlaylistOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel operation failed..
        /// </summary>
        internal static string CatalogOperationFailed {
            get {
                return ResourceManager.GetString("CatalogOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} — {2} channels found..
        /// </summary>
        internal static string CatalogPageStatus {
            get {
                return ResourceManager.GetString("CatalogPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language has been changed. Do you want to restart the application to apply the changes?.
        /// </summary>
        internal static string ChangedLanguageRestartApplicationQuestion {
            get {
                return ResourceManager.GetString("ChangedLanguageRestartApplicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the application language to &apos;{0}&apos;?.
        /// </summary>
        internal static string ChangeLanguageQuestion {
            get {
                return ResourceManager.GetString("ChangeLanguageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom channel &apos;{0}&apos; saved..
        /// </summary>
        internal static string CustomChannelSaved {
            get {
                return ResourceManager.GetString("CustomChannelSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the custom channel &apos;{0}&apos;? This cannot be undone..
        /// </summary>
        internal static string DeleteCustomChannelQuestion {
            get {
                return ResourceManager.GetString("DeleteCustomChannelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the playlist &apos;{0}&apos;? This cannot be undone..
        /// </summary>
        internal static string DeletePlaylistQuestion {
            get {
                return ResourceManager.GetString("DeletePlaylistQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the application?.
        /// </summary>
        internal static string ExitApplicationQuestion {
            get {
                return ResourceManager.GetString("ExitApplicationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Playlist.
        /// </summary>
        internal static string ExportPlaylistTitle {
            get {
                return ResourceManager.GetString("ExportPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Playlist.
        /// </summary>
        internal static string ImportPlaylistTitle {
            get {
                return ResourceManager.GetString("ImportPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Playlist.
        /// </summary>
        internal static string MergePlaylistTitle {
            get {
                return ResourceManager.GetString("MergePlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Channel.
        /// </summary>
        internal static string NewCustomChannelName {
            get {
                return ResourceManager.GetString("NewCustomChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Playlist.
        /// </summary>
        internal static string NewPlaylistName {
            get {
                return ResourceManager.GetString("NewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PageStatus {
            get {
                return ResourceManager.GetString("PageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist cannot be saved: {0}.
        /// </summary>
        internal static string PlaylistCannotBeSaved {
            get {
                return ResourceManager.GetString("PlaylistCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entries have no URL..
        /// </summary>
        internal static string PlaylistEntriesWithoutUrl {
            get {
                return ResourceManager.GetString("PlaylistEntriesWithoutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; exported to &apos;{1}&apos;..
        /// </summary>
        internal static string PlaylistExported {
            get {
                return ResourceManager.GetString("PlaylistExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; imported..
        /// </summary>
        internal static string PlaylistImported {
            get {
                return ResourceManager.GetString("PlaylistImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist needs a name..
        /// </summary>
        internal static string PlaylistNameRequired {
            get {
                return ResourceManager.GetString("PlaylistNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist operation failed..
        /// </summary>
        internal static string PlaylistOperationFailed {
            get {
                return ResourceManager.GetString("PlaylistOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist &apos;{0}&apos; saved..
        /// </summary>
        internal static string PlaylistSaved {
            get {
                return ResourceManager.GetString("PlaylistSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playlist &apos;{0}&apos; has unsaved changes. Do you want to save them?.
        /// </summary>
        internal static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
    }
}
