//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB84.IPTV.M3U.Editor.Infrastructure.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BB84.IPTV.M3U.Editor.Infrastructure.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;channel&quot;:&quot;AnimalPlanetEast.us&quot;,&quot;reason&quot;:&quot;dmca&quot;,&quot;ref&quot;:&quot;https://github.com/iptv-org/iptv/issues/1831&quot;}].
        /// </summary>
        internal static string BlocklistJson {
            get {
                return ResourceManager.GetString("BlocklistJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;documentary&quot;,&quot;name&quot;:&quot;Documentary&quot;,&quot;description&quot;:&quot;Programming that depicts a person or real-world event&quot;}].
        /// </summary>
        internal static string CategoryJson {
            get {
                return ResourceManager.GetString("CategoryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;alt_names&quot;: [&quot;安徽卫视&quot;],&quot;categories&quot;: [&quot;general&quot;],&quot;closed&quot;: &quot;2020-05-31&quot;,&quot;country&quot;: &quot;CN&quot;,&quot;id&quot;: &quot;AnhuiTV.cn&quot;,&quot;is_nsfw&quot;: false,&quot;launched&quot;: &quot;2016-07-28&quot;,&quot;name&quot;: &quot;Anhui TV&quot;,&quot;network&quot;: &quot;Anhui&quot;,&quot;owners&quot;: [&quot;China Central Television&quot;],&quot;replaced_by&quot;: &quot;CCTV1.cn&quot;,&quot;website&quot;: &quot;http://www.ahtv.cn/&quot;}].
        /// </summary>
        internal static string ChannelJson {
            get {
                return ResourceManager.GetString("ChannelJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;code&quot;:&quot;CNYAT&quot;,&quot;country&quot;:&quot;CN&quot;,&quot;name&quot;:&quot;Yantai&quot;,&quot;subdivision&quot;:&quot;CN-SD&quot;,&quot;wikidata_id&quot;:&quot;Q210493&quot;}].
        /// </summary>
        internal static string CityJson {
            get {
                return ResourceManager.GetString("CityJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;code&quot;:&quot;CA&quot;,&quot;flag&quot;:&quot;🇨🇦&quot;,&quot;languages&quot;:[&quot;eng&quot;,&quot;fra&quot;],&quot;name&quot;:&quot;Canada&quot;}].
        /// </summary>
        internal static string CountryJson {
            get {
                return ResourceManager.GetString("CountryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;alt_names&quot;:[&quot;Paris Île-de-France&quot;],&quot;broadcast_area&quot;:[&quot;c/FR&quot;],&quot;channel&quot;:&quot;France3.fr&quot;,&quot;format&quot;:&quot;576i&quot;,&quot;id&quot;:&quot;ParisIledeFrance&quot;,&quot;is_main&quot;:false,&quot;languages&quot;:[&quot;fra&quot;],&quot;name&quot;:&quot;Paris Ile-de-France&quot;,&quot;timezones&quot;:[&quot;Europe/Paris&quot;]}].
        /// </summary>
        internal static string FeedJson {
            get {
                return ResourceManager.GetString("FeedJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;channel&quot;:&quot;BBCOne.uk&quot;,&quot;feed&quot;:&quot;EastMidlandsHD&quot;,&quot;lang&quot;:&quot;en&quot;,&quot;site&quot;:&quot;sky.co.uk&quot;,&quot;site_id&quot;:&quot;bbcone&quot;,&quot;site_name&quot;:&quot;BBC One&quot;}].
        /// </summary>
        internal static string GuideJson {
            get {
                return ResourceManager.GetString("GuideJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;French&quot;,&quot;code&quot;:&quot;fra&quot;}].
        /// </summary>
        internal static string LanguageJson {
            get {
                return ResourceManager.GetString("LanguageJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;channel&quot;:&quot;France3.fr&quot;,&quot;feed&quot;:&quot;ParisIledeFrance&quot;,&quot;format&quot;:&quot;SVG&quot;,&quot;height&quot;:468,&quot;tags&quot;:[&quot;horizontal&quot;,&quot;white&quot;],&quot;url&quot;:&quot;https://example.com/logo.svg&quot;,&quot;width&quot;:1000}].
        /// </summary>
        internal static string LogoJson {
            get {
                return ResourceManager.GetString("LogoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;code&quot;:&quot;MAGHREB&quot;,&quot;countries&quot;:[&quot;DZ&quot;,&quot;LY&quot;,&quot;MA&quot;,&quot;MR&quot;,&quot;TN&quot;],&quot;name&quot;:&quot;Maghreb&quot;}].
        /// </summary>
        internal static string RegionJson {
            get {
                return ResourceManager.GetString("RegionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;channel&quot;:&quot;France3.fr&quot;,&quot;feed&quot;:&quot;NordPasdeCalaisHD&quot;,&quot;quality&quot;:&quot;720p&quot;,&quot;referrer&quot;:&quot;http://example.com/&quot;,&quot;title&quot;:&quot;France 3 Nord Pas-de-Calais HD&quot;,&quot;url&quot;:&quot;http://1111296894.rsc.cdn77.org/LS-ATL-54548-6/index.m3u8&quot;,&quot;user_agent&quot;:&quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64)&quot;}].
        /// </summary>
        internal static string StreamJson {
            get {
                return ResourceManager.GetString("StreamJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;code&quot;:&quot;BD-01&quot;,&quot;country&quot;:&quot;BD&quot;,&quot;name&quot;:&quot;Bandarban&quot;,&quot;parent&quot;:&quot;BD-B&quot;}].
        /// </summary>
        internal static string SubdivisionJson {
            get {
                return ResourceManager.GetString("SubdivisionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;countries&quot;:[&quot;UK&quot;,&quot;GG&quot;,&quot;IM&quot;,&quot;JE&quot;],&quot;id&quot;:&quot;Europe/London&quot;,&quot;utc_offset&quot;:&quot;+00:00&quot;}].
        /// </summary>
        internal static string TimezoneJson {
            get {
                return ResourceManager.GetString("TimezoneJson", resourceCulture);
            }
        }
    }
}
