<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ApplicationIcon>Application.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Equals('Release'))">
		<IncludeAllContentForSelfExtract>False</IncludeAllContentForSelfExtract>
		<IncludeNativeLibrariesForSelfExtract>True</IncludeNativeLibrariesForSelfExtract>
		<OutputType>WinExe</OutputType>
		<PublishSingleFile>True</PublishSingleFile>
	</PropertyGroup>
	<ItemGroup>
		<AvaloniaResource Include="Application.ico" />
		<AvaloniaResource Include="Resources\*.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Controls.DataGrid" />
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Svg.Controls.Skia.Avalonia" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BB84.IPTV.M3U.Editor.Infrastructure\BB84.IPTV.M3U.Editor.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Condition="$(Configuration.Equals('Debug'))" Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Condition="$(Configuration.Equals('Release'))" Update="appsettings.Production.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>