<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ApplicationIcon>Application.ico</ApplicationIcon>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net10.0-windows</TargetFrameworks>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<UseWPF>true</UseWPF>
		<StartupObject>BB84.IPTV.M3U.Editor.App</StartupObject>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.Equals('Release'))">
		<IncludeAllContentForSelfExtract>False</IncludeAllContentForSelfExtract>
		<IncludeNativeLibrariesForSelfExtract>True</IncludeNativeLibrariesForSelfExtract>
		<OutputType>WinExe</OutputType>
		<PublishSingleFile>True</PublishSingleFile>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="Application.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>
	<ItemGroup>
		<Page Include="App.xaml" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BB84.IPTV.M3U.Editor.Infrastructure\BB84.IPTV.M3U.Editor.Infrastructure.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<None Condition="$(Configuration.Equals('Debug'))" Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Condition="$(Configuration.Equals('Release'))" Update="appsettings.Production.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>